export const SEO_BLOG_BANNER_CLIENT_WEBSITES: Record<string, string> = {
  "Bchu Runway": "https://bchurunway.com",
  Mamarine: "https://mamarinethailand.com",
  Tangmo: "https://www.tangmo.clothing",
  Modernform: "https://www.modernform.co.th",
  Easymoney: "https://www.easymoney.co.th",
  "Smile Seasons Dental Clinic": "https://smileseasons.co",
  "Woo Tender": "https://wootenderthailand.com",
  "Grand Home Mart": "https://grandhomemart.com",
  "SCB 10X": "https://scb10x.com",
  "Convert Cake Ads": "https://convertcake.com",
  InnovestX: "https://www.innovestx.co.th",
  Thonglorpet: "https://thonglorpet.com",
  "First Step": "https://mrflexx.com",
  "Parin Thailand": "https://www.parinthailand.com",
  Tempur: "https://th.tempur.com",
  DBP: "https://dbp.co.th",
  Lingoace: "https://www.lingoace.com",
  "Money DD": "https://www.goodmoneybygsb.com",
  "EVA Airways": "https://www.evaair.com",
  "Villa Market": "https://www.villamarket.com",
  "CHOW SOCIAL": "https://chow-social.com",
  "Recovery and Wellness": "https://formrecovery.com",
  "Sarnies Coffee": "https://sarnies.com",
  "Swiss Lab": "https://pureplus.co.th",
  "Dr Tan Clinic": "https://doctortanclinic.com",
  Playboy: "https://www.playboyfashionth.com",
  Orbix: "https://www.orbixinvest.com",
  "Patama clinic": "https://ptmclinic.com",
  "La Posh": "https://laposhclinic.com",
  "Kowa CCTV": "https://www.jr.co.th",
  "Mali Clinic": "https://scmcthailand.com",
  Aloex: "https://aloexhair.com",
  Mogen: "https://mogen.co.th",
  "Siam Takashimaya": "https://www.siamtakashimaya.co.th",
  "Little Shield": "https://little-shield.com",
  ABB: "https://abb.co.th",
  "Radiance Skin Clinic": "https://radianceskinclinic.com",
  "Major Mavista Phromphong": "https://www.mjd.co.th",
  StashAway: "https://stashaway.co.th",
  "Aestheta Clinic": "http://aestheta.co",
  Hotelsup: "https://www.hotelsup.co",
  Sealy: "https://sealythailand.com",
  "Recovery me": "https://recoverymeclinic.com",
  "Peep Share": "https://peepshare.com",
  "Jacob Leather Bags": "https://jacob.co.th",
  "MJD Maru Chula": "https://www.mjd.co.th",
  "NBD Healthcare ADS": "https://nbdhealthcare.com",
  "Base Play house": "https://baseplayhouse.co",
  "De Beau Clinic": "https://debeauclinic.com",
  "Doitung Club": "https://doitung.com",
  sendo: "http://sendothailand.jp",
  champacawood: "https://champacawood.com",
  "Khui AI": "https://khuiai.com",
  "pasta ama LINE": "https://openlink.co/pastaama",
  Eritoileto: "https://www.eritoileto.com",
  "TRUE Business": "https://true.th/business",
  "tissue chonburi tiktok consult": "https://tissuechonburi.com",
  Okya: "https://okya.co",
  "Vantage Markets": "https://www.vantagemarkets.com",
  SleepHappy: "https://sleephappy.co.th",
  "dime tiktok consult": "https://dime.co.th",
  "Thermomix TH": "https://thermomix.co.th",
  SIS: "https://sisthai.com",
  "HRC SEO": "https://www.thaihonda.co.th",
  "BFill Clinic": "https://bfillclinic.com",
  "The Next": "https://thenextoptical.com",
  "THAI AIRWAYS": "https://www.thaiairways.com",
  "M Factors": "http://www.mfactors.co.th",
  "Zenity X": "https://zenityx.ai",
  "Toyota Buzz": "https://www.toyotabuzz.com",
  Reeve: "https://reevebeachclubkrabi.com",
  "Babyhills TH": "https://babyhillsthailand.com",
  "Angel's Secret": "https://angelsecret.net",
  "It’S SKIN": "https://www.itsskinthailand.com",
  Smilebloom: "https://mamicos.com/product-category/smilebloom",
  Mami: "https://www.mamicos.com",
  Thaisyncon: "https://www.thaisyncon.com",
  "Nara Stainless": "https://narastainless.com",
  "B Autohaus": "https://bautohaus.com",
  "Double V Group": "https://doublev.group",
  Elitile: "http://www.elitile.co.th",
  Dakok: "https://dakok.com",
  Siammittraphap: "http://www.siammittraphap.com",
  Provamed: "https://provamed.co.th",
  "SFC Thailand": "https://www.sfcthai.com",
  "TRUE Business Tiktok": "https://true.th/business",
  "Siam Takashimaya 2": "https://www.siamtakashimaya.co.th",
  "AT U DENTAL": "https://www.atudental.co.th",
  "Alena D": "https://alenadevelopment.com",
  "Meko Skin Care": "https://mekoclinic.com",
  "Thunder solution": "https://thunder.in.th",
  "Siam Pearl Property": "https://siampearlproperty.com",
  "Muniq charoenkrung": "https://www.mjd.co.th",
  Buildman: "https://buildman.biz",
  "Movefast JSP": "https://movefast.me",
  "Movefast Aelova": "https://aelova.com",
  Tabienpharuay: "https://tabienpharuay.com",
  "TCL 2026": "https://www.tcl.com/th",
  Thaya: "https://thayahotel.com",
  Phufaresthome: "https://www.phufaresthome.com",
  "Nura Thailand": "https://nurasound.com",
  "Movefast Pamu": "https://movefast.me",
  Dortmuend: "https://dortmuend.com",
  "ALTERNATE TAB ADVERTISING": "http://alttabadvertising.com",
  Luciaka: "https://ibeautythailand.com",
  "Starmark Work Space": "http://starmark.co.th",
  Dermatiks: "https://dermatix.co.th",
  "STARMARK kitchen": "http://starmark.co.th",
  Sewa: "https://sewathailand.com",
}

export function getSeoBlogBannerWebsite(clientName?: string | null) {
  if (!clientName) return ""
  const normalized = clientName.trim().toLowerCase()
  const match = Object.entries(SEO_BLOG_BANNER_CLIENT_WEBSITES).find(
    ([name]) => name.trim().toLowerCase() === normalized,
  )
  return match?.[1] || ""
}
